name: 1. build

on:
  push:
    branches:
      - develop
  pull_request:
    branches: [master, develop]

env:
  LANG: "en_US.UTF-8"

jobs:
  export:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: set locale
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8
      - name: checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: create executables
        uses: firebelley/godot-export@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          GODOT_MONO_FILE_VERSION: 3.3.3-stable
          GODOT_MONO_URL_VERSION: 3.3.3
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_MONO_URL_VERSION}}/mono/Godot_v${{env.GODOT_MONO_FILE_VERSION}}_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_MONO_URL_VERSION}}/mono/Godot_v${{env.GODOT_MONO_FILE_VERSION}}_mono_export_templates.tpz
          relative_project_path: ./
          archive_export_output: true
          create_release: false
      - name: upload executables
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: ~/.local/share/godot/dist/*.zip
