name: deploy

on:
  release:
    types: [created, edited]

jobs:
  deploy_mac:
    name: Deploy Mac executable to itch.io
    runs-on: ubuntu-latest
    steps:
      - name: Download Mac executable from GitHub release
        id: download_mac
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tag/${{ github.event.release.tag_name }}
          file: coa-mac.zip
      - name: Publish Mac executable to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: coa
          ITCH_USER: forerunnergames
          PACKAGE: build/mac
          VERSION: ${{ steps.download_mac.outputs.version }}

  deploy_windows:
    name: Deploy Windows executable to itch.io
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows executable from GitHub release
        id: download_windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tag/${{ github.event.release.tag_name }}
          file: coa-windows.zip
      - name: Publish Windows executable to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: coa
          ITCH_USER: forerunnergames
          PACKAGE: build/windows
          VERSION: ${{ steps.download_windows.outputs.version }}

  deploy_linux:
    name: Deploy Linux executable to itch.io
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux executable from GitHub release
        id: download_linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tag/${{ github.event.release.tag_name }}
          file: coa-linux.zip
      - name: Publish Linux executable to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: coa
          ITCH_USER: forerunnergames
          PACKAGE: build/linux
          VERSION: ${{ steps.download_linux.outputs.version }}