name: deploy

on:
  release:
    types: [created, edited]

jobs:
  deploy_mac:
    name: deploy mac
    runs-on: ubuntu-latest
    steps:
      - name: download mac
        id: download_mac
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ github.event.release.tag_name }}
          file: coa-mac.zip
      - name: publish mac
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: coa
          ITCH_USER: forerunnergames
          PACKAGE: coa-mac.zip
          VERSION: ${{ steps.download_mac.outputs.version }}

  deploy_windows:
    name: deploy windows
    runs-on: ubuntu-latest
    steps:
      - name: download windows
        id: download_windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ github.event.release.tag_name }}
          file: coa-windows.zip
      - name: publish windows
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: coa
          ITCH_USER: forerunnergames
          PACKAGE: coa-windows.zip
          VERSION: ${{ steps.download_windows.outputs.version }}

  deploy_linux:
    name: deploy linux
    runs-on: ubuntu-latest
    steps:
      - name: download linux
        id: download_linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ github.event.release.tag_name }}
          file: coa-linux.zip
      - name: publish linux
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: coa
          ITCH_USER: forerunnergames
          PACKAGE: coa-linux.zip
          VERSION: ${{ steps.download_linux.outputs.version }}

  cleanup:
    name: cleanup
    runs-on: ubuntu-latest
    steps:
      - name: delete github executables
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          tag: tags/${{ github.event.release.tag_name }}
          assets: 'coa-*.zip'
