name: export

on:
  push:
    branches:
      - master

jobs:
  export:
    name: export executables
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: install .net sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: use custom editor settings
        run: cp default_env.tres ~/.config/godot/editor_settings-3.tres
      - name: create executables
        uses: firebelley/godot-export@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          GODOT_MONO_FILE_VERSION: 3.3-rc8
          GODOT_MONO_URL_VERSION: 3.3/rc8
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_MONO_URL_VERSION}}/mono/Godot_v${{env.GODOT_MONO_FILE_VERSION}}_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_MONO_URL_VERSION}}/mono/Godot_v${{env.GODOT_MONO_FILE_VERSION}}_mono_export_templates.tpz
          relative_project_path: ./
          archive_export_output: true
          create_release: false
          base_version: 0.0.1